Add docker database to projects
srs-saros/backend pull request #4
Opened 2021-07-01 09:12 UTC by sebmancipe

## Description

Is needed to add a container to be used as database support in local development. This container can be easily deployable when production requires.

## Motivation and Context

Is needed to create a PostgreSQL database to start using the project itself.

## Screenshots

Doesn't apply

## Impact

None.

- Does this change "could break" something? What could break?:

None.

- What services/users/activities are affected by this change?

None

2021-07-03 14:40 UTC, jinfanv commented on packages/server/knexfile.ts
> +      database: 'backend',
Esto debe ir como una variable del sistema: ejemplo, con process.env

2021-07-03 14:44 UTC, jinfanv requested changes

2021-07-03 14:44 UTC, jinfanv commented on packages/server/knexfile.ts
> +      database: 'backend',
Esto debe ir como una variable del sistema: ejemplo, con process.env @sebmancipe

2021-07-05 09:56 UTC, sebmancipe commented on packages/server/knexfile.ts
> +      database: 'backend',
Alredy fixed @jinfanv

2021-07-07 01:35 UTC, jinfanv requested changes

2021-07-07 01:35 UTC, jinfanv commented on packages/server/knexfile.ts
> +  }
@sebmancipe No logro visualizar el cambio, pero no se si es que no se como ver los cambios porque sigo viendo que los valores de producción siguen quemados. 

`production: {
    client: 'postgresql',
    connection: {
      database: 'backend',
      user: 'root',
      password: 'root'
    }`

2021-07-07 01:37 UTC, jinfanv approved these changes

2021-07-10 02:49 UTC, NICOLUKAS approved these changes

2021-07-10 03:06 UTC, merged